version: '3.8'
services:
  db:
    image: postgres:15
    container_name: dunnas-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dunnas_condominio
    ports:
      - "5433:5432"